DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS points;

CREATE TABLE users(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  unique_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  nickname Text
);

CREATE TABLE points(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  player_id TEXT NOT NULL REFERENCES users (unique_id),
  points INTEGER NOT NULL
);

